Evaluation - Hadley master class

========================================================

## Examine subset function
```{r examine-subset}
subset(mtcars, cyl == 4)
# vs.
mtcars[mtcars$cyl == 4, ]
# How does it work?
subset <- function(x, condition) {
  condition_call <- substitute(condition)
  r <- eval(condition_call, x, parent.frame())
  x[r, ]
}
condition_call <- substitute(cyl == 4)
r <- eval(condition_call, mtcars, parent.frame())
mtcars[r,]
```

## Quoting
```{r quoting}
x <- quote(vs == am)
x
# vs == am
str(x)
# language vs == am
is.language(x)
# [1] TRUE
is.call(x)
# [1] TRUE
is.expression(x)
# [1] FALSE

call("==", "vs", "am")
call("==", vs, am)
call("==", as.name("vs"), as.name("am"))

x <- parse(text = "vs == am")
x
is.expression(x)
# [1] TRUE
# Expressions are a list of calls/symbols
x[[1]]
# vs == am
is.call(x[[1]])
# [1] TRUE
```

Why won't this work?
```{r why-wont-this-work-subset}
subset2 <- function(x, condition) {
  quote(condition)
}
subset2(mtcars, cyl == 8)
condition <- quote(cyl==8)
condition
condition <- substitute(cyl==8)


```

Subset - cont'd
```{r subset-2}
subset <- function(x, condition) {
  match.call()
}
subset(mtcars, vs == am)
# subset(x = mtcars, condition = vs == am)
subset <- function(x, condition) {
  match.call()$condition
}
subset(mtcars, vs == am)
# subset(x = mtcars, condition = vs == am)

subset <- function(x, condition) {
  substitute(condition)
}
subset(mtcars, vs == am)
# Uses lazy evaluation and extracts
# call from promise/thunk
# Also has other uses
```

## Evaluating
Evaluate in a data frame environment (not global environment)
```{r evaluate-1}
# Given a call and an environment (or something like
# an environment like a list or data frame), eval
# will evaluate the call in that environment
rm(list=ls())
x <- quote(vs == am)
eval(x, globalenv())
eval(x, mtcars)  # evaluates in mtcars environment! COOL!
# What will happen when I run this code?
eval(vs == am, mtcars)
eval(quote(vs == am), mtcars)

subset <- function(x, condition) {
  condition_call <- substitute(condition)
  r <- eval(condition_call, x)
  x[r, ]
}
subset(mtcars, cyl == 4)
# It works!
```

## Scoping
```{r scoping-1}
rm(list=ls())
# What should this do?
x <- 4
subset(mtcars, cyl == x)
y <- 4
subset(mtcars, cyl == y)
# What does it do?
# Why?
```

```{r scoping-2}
# We need to tell eval where to look if the
# variables aren't found in the data frame.
# We need to provide the equivalent of a parent
# environment.  That’s the third argument to eval
subset <- function(x, condition) {
  condition_call <- substitute(condition)
  r <- eval(condition_call, x, parent.frame())
  x[r, ]
}
# parent.frame() finds the environment in which
# the current function is being executed

x <- 4
f1 <- function() {
  x <- 6
  subset(mtcars, cyl == x)
}
f1()
f2 <- function() {
  x <- 8
  subset(mtcars, cyl == get("x"))
}
f2()
```

```{r scoping-3}
# An alternative approach would be to use a formula
# Formulas quote and capture the environment in
# which they are defined
subset <- function(x, f) {
  r <- eval(f[[2]], x, environment(f))
  x[r, ]
}
subset(mtcars, ~ cyl == x)
# Using formulas has the advantage that it's
# very obvious that something non-standard is
# going on
```

## Good for interactive, but not programming
```{r not-good-for-programming}
# All these functions are useful for interactive
# data analysis, but ARE NOT suitable for
# programming with.
rm(list=ls())
scramble <- function(x) x[sample(nrow(x)), ]
scramble(mtcars)
subscramble <- function(x, condition) {
  scramble(subset(x, condition))
}
subscramble(mtcars, cyl == 4)
debugonce(subset)
subscramble(mtcars, cyl == 4)
```

## Computing on the language
```{r computing-on-lang}
# How can we call a function that uses non-standard
# evaluation?
rm(list=ls())
library(lattice)
xyplot(disp ~ mpg, data = mtcars)
x <- "disp"
y <- "mpg"
xyplot(x ~ y, data = mtcars)

# Second use of substitute: modifying calls
# Extremely useful when, for whatever reason, you
# need to create a call as if you had typed that
# code directly into the command line
substitute(x ~ y, list("x" = x, "y" = y))
substitute(a ~ b, list("a" = as.name(x), "b" = as.name(y)))
eval(substitute(a ~ b, list("a" = as.name(x), "b" = as.name(y))))

f <- substitute(x ~ y, list(x = as.name(x),
  y = as.name(y)))
class(f)
xyplot(f, data = mtcars)
f <- eval(substitute(x ~ y, list(x = as.name(x),
  y = as.name(y))))
class(f)
xyplot(f, data = mtcars)
eval(substitute(xyplot(x ~ y, data = mtcars),
  list(x = as.name(x), y = as.name(y))))
```

## Calls are trees - Behave like lists
```{r call-are-trees}
# calls are trees, and behave like lists
x <- quote(a * (b + 1))
# First piece is name of function being called
# like lisp, sml? (function, arg1, arg2, ...)
x[[1]]
# Subsequent pieces are arguments (language objects)
as.list(x[-1])
as.list(x)
x[[2]]
x[[3]]
x[[3]][[1]]
x[[3]][[2]]
x[[3]][[2]][[1]]
x[[3]][[2]][[2]]
x[[3]][[2]][[3]]
x[[3]][[2]][[4]]
```

```{r calls-are-trees-2}
# can modify calls
x <- quote(a * (b + 1))
x
as.list(x)
x[[1]] <- as.name("c")
x
x[[1]] <- as.name("*")
x
y <- quote(lm(formula = disp ~ mpg, data = mtcars))
y
as.list(y)
y$formula <- quote(price ~ carat)
as.list(y)
y

y$data <- quote(diamonds)
y
# See 2-draw-tree.r for an example that
# draws call trees in a more informative manner.
```

## Rewrite write.csv
```{r rewrite-write-csv}
#  Call <- match.call(expand.dots = TRUE)
#     for (argname in c("append", "col.names", "sep", "dec", "qmethod")) if (!is.null(Call[[argname]])) 
#         warning(gettextf("attempt to set '%s' ignored", argname), 
#             domain = NA)
#     rn <- eval.parent(Call$row.names)
#     Call$append <- NULL
#     Call$col.names <- if (is.logical(rn) && !rn) 
#         TRUE
#     else NA
#     Call$sep <- ","
#     Call$dec <- "."
#     Call$qmethod <- "double"
#     Call[[1L]] <- as.name("write.table")
#     eval.parent(Call)
my.write.csv <- function (...) {
  Call <- match.call(expand.dots = TRUE)
  for (argname in c('append', 'col.names', 'sep', 'dec', 'qmethod'))
    if (!is.null(Call[[argname]])) warning(gettextf("attempt to set '%s' ignored", argname), domain=NA)
#   Call
}
my.write.csv('abc', append=FALSE, sep=',', dec='no', junk=TRUE)
```
